---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testapp2
    spec:
      containers:
      - name: testapp3
        image: testapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: testapp2